# Generated by Django 4.2.6 on 2024-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
